name: Commitlint
on: [pull_request]
jobs:
  commitlint:
    if: github.actor != 'trustify-ci-bot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
