name: Multiple Architecture Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "v*"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-build:
    uses: ./.github/workflows/build-push-images.yaml
    with:
      registry: "ghcr.io"
      image_name: "${{ github.repository_owner }}/trustify-ui"
      containerfile: "./Containerfile"
      architectures: '[ "amd64", "arm64", "ppc64le", "s390x" ]'
      extra-args: "--ulimit nofile=4096:4096"
      pre_build_cmd: |
        sed -i '/RUN npm clean-install/i RUN npm install -g npm@9' Containerfile
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}