name: Test-Issue-14

on:
  push:
    branches:
      - main
      - "release-*"
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
  ci:
    name: issue-14
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4      
      - name: Build Dockerfile
        run: docker build -t ui -f Dockerfile .
      